[client]
toolbarMode = "minimal"


[theme]

base = "light"
primaryColor = "#e63e3e"
backgroundColor = "white"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#111111"
borderColor = "#dddddd"
showWidgetBorder = true

[theme.light.sidebar]
backgroundColor = "#f3f3f3"
secondaryBackgroundColor = "#e9e9e9"
borderColor = "#dddddd"


# Custom DARK theme
[theme.dark]
primaryColor = "#e63e3e"
backgroundColor = "#212121"
secondaryBackgroundColor = "#2f2f2f"
textColor = "#ececec"
borderColor = "#4d4d4f"
showWidgetBorder = false

[theme.dark.sidebar]
backgroundColor = "#171717"
secondaryBackgroundColor = "#2f2f2f"
borderColor = "#4d4d4f"